nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

# TODO: Maybe remove it with future package version
# https://github.com/vercel/next.js/issues/38939
packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: '*'


yarnPath: .yarn/releases/yarn-3.5.1.cjs
